global_frame: "map"

input_image:
  width: 2048 #Full image size. DOWNSAMPLED image must be divisable by 32
  height: 1536
  decimation: 4

image_downsample: 1
optical_flow_win_size: 21


edge_threshold: 31
patch_size: 31

bucket_size: 25
features_per_bucket: 1
