global_frame: "map"

input_image:
  width: 2048 #Full image size. DOWNSAMPLED image must be divisable by 32
  height: 1536
  decimation: 1


# left_info: PointGreyLeft
# right_info: PointGreyRight

image_downsample: 2
optical_flow_win_size: 41


edge_threshold: 15
patch_size: 15

bucket_size: 25
features_per_bucket: 1
