global_frame: "map"

image_downsample: 1 #Downsample to be done IN LINE. Set to '1' if downsample is done elsewhere
optical_flow_win_size: 21 

edge_threshold: 31
patch_size: 31

bucket_size: 25
features_per_bucket: 1
