global_frame: "map"

input_image:
  width: 1024 #Full image size. DOWNSAMPLED image must be divisable by 32
  height: 768
  decimation: 1


left_info: PointGreyLeftDownsample
right_info: PointGreyRightDownsample

image_downsample: 1
optical_flow_win_size: 41


edge_threshold: 15
patch_size: 15

bucket_size: 25
features_per_bucket: 1
